#!/bin/bash

virtualenv -p python3 shiksha-buddy-venv
pip install --upgrade virtualenv
source shiksha-buddy-venv/bin/activate
pip install -r requrements.txt
echo "Enter MySQL username: "
read -r mysql_username
echo "create database `shiksha_buddy`" | mysql -u $mysql_username -p
npm i
