# Generated by Django 2.2.7 on 2020-01-01 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('site_id', models.CharField(max_length=50)),
                ('page_name', models.CharField(max_length=80)),
                ('title', models.CharField(blank=True, max_length=50)),
                ('heading', models.CharField(blank=True, max_length=250)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, default=None, max_digits=9)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9)),
                ('address', models.CharField(blank=True, max_length=250)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('email', models.CharField(blank=True, max_length=30)),
                ('facebook_link', models.CharField(blank=True, max_length=50)),
                ('twitter_link', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TextImagePage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('site_id', models.CharField(max_length=50)),
                ('page_name', models.CharField(max_length=80)),
                ('title', models.CharField(blank=True, max_length=50)),
                ('heading', models.CharField(blank=True, max_length=250)),
                ('image', models.CharField(blank=True, max_length=100)),
                ('text', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
