# Generated by Django 2.2.7 on 2019-12-31 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericPage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('site_id', models.CharField(max_length=50)),
                ('page_name', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=50)),
                ('heading', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('genericpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='admin_panel.GenericPage')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('address', models.CharField(max_length=250)),
                ('phone', models.PositiveIntegerField()),
                ('email', models.CharField(max_length=30)),
                ('facebook_link', models.CharField(max_length=50)),
                ('twitter_link', models.CharField(max_length=50)),
            ],
            bases=('admin_panel.genericpage',),
        ),
        migrations.CreateModel(
            name='TextImagePage',
            fields=[
                ('genericpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='admin_panel.GenericPage')),
                ('image', models.CharField(max_length=100)),
                ('text', models.TextField()),
            ],
            bases=('admin_panel.genericpage',),
        ),
    ]
