# Generated by Django 2.2.7 on 2020-01-03 12:50

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('site_id', models.CharField(max_length=50)),
                ('children', django_mysql.models.JSONField(default=dict)),
            ],
        ),
    ]
